### ISSUE TITLE
Implement Sql Connection

### ISSUE THREAD

**Issue by rima1881** [rima1881/Flat-Earthers-Backend#8]

**Comment by bryjen** [comment]
Right now, I've created a MySQL db hosted in google cloud and have connected some of the backend's functionality to the db. As of right now, 3/4s of user functionality have been adapted to this cloud db. 

Db Specifics:
- It uses one of the least expensive configs possible (~15 cents per active hour without deductions)
- Chose MySQL over SQL sever because it, apparently, has faster reads (our app is going to be a read heavy application) and microsoft SQL server needs a license (didn't really double check this).

**Comment by bryjen** [comment]
This [commit](https://github.com/rima1881/Flat-Earthers-Backend/commit/8cf900fc58f4c632c7a8166afa7046dff2ddfb14) adds tested functionality for the targets service to perform operations on the google cloud db mentioned above.

We chillin
